theme: jekyll-theme-architect
logo: /res/iamal_144.png
title: iamal
remote_theme: amalbenny/iamal-template@iv0.1.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
